services:
  immich-photo-mosaic:
    image: turbopolar/immich-photo-mosaic:latest
    container_name: immich-photo-mosaic
    user: "1000:1000"
    ports:
      - "5465:5777"
    environment:
      IMMICH_API_KEY: ${IMMICH_API_KEY}
      IMMICH_BASE_URL: ${IMMICH_BASE_URL}
    volumes:
      - ./config:/app/config
      - ./output:/app/output
    restart: unless-stopped
